Projekt-Programowanie/Controllers/CrossController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Projekt_Programowanie.Data;
using Projekt_Programowanie.Interfaces;
using Projekt_Programowanie.Models;
using Projekt_Programowanie.Models.MODELS;
using Projekt_Programowanie.Repository;

namespace Projekt_Programowanie.Controllers
{
    public class CrossController : Controller
    {
        private readonly ICrossRepository _crossRepository;
        public CrossController(ICrossRepository crossRepository)
        {
            _crossRepository = crossRepository;
        }
        public async Task<IActionResult> Cross()
        {
            var crosses = await _crossRepository.GetKrzyzowki();
            return View(crosses);
        }

        public async Task<IActionResult> Generator()
        {
            var tab = await _crossRepository.generowanie(2);
            string data1 = HttpContext.Request.Form["odp1"];
            string data2 = HttpContext.Request.Form["odp2"];
            string data3 = HttpContext.Request.Form["odp3"];
            string data4 = HttpContext.Request.Form["odp4"];
            string data5 = HttpContext.Request.Form["odp5"];
            string data6 = HttpContext.Request.Form["odp6"];
            if (data1 != null)
                tab = _crossRepository.wprowadzenieSlowa(data1, tab, 100016);
            if (data2 != null)
                tab = _crossRepository.wprowadzenieSlowa(data2, tab, 201005);
            if (data3 != null)
                tab = _crossRepository.wprowadzenieSlowa(data3, tab, 100037);
            if (data4 != null)
                tab = _crossRepository.wprowadzenieSlowa(data4, tab, 204006);
            if (data5 != null)
                tab = _crossRepository.wprowadzenieSlowa(data5, tab, 102057);
            if (data6 != null)
                tab = _crossRepository.wprowadzenieSlowa(data6, tab, 206025);
            return View(tab);
        }
        [HttpPost]
        public IActionResult Sprawdzam(GenerowanaKrzyzowka tab)
        {
            if (_crossRepository.sprawdzanie(tab) == true)
            {
                return View("Gratulacje"); // Przekierowanie do widoku gratulacyjnego
            }
            return View("Zla"); 
        }
        public IActionResult Gratulecje()
        {
            return View();
        }
        public IActionResult Zla()
        {
            return View();
        }
    }
    }

Projekt-Programowanie/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Projekt_Programowanie.Models;
using System.Diagnostics;

namespace Projekt_Programowanie.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Dodaj()
        {
            return View();
        }
        public IActionResult Lista()
        {
            return View();
        }
        public IActionResult Generator1()
        {
            return View();
        }

        public IActionResult Autorzy()
        {
            return View();
        }
        public IActionResult Opis()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Listy()
        {
            return View();
        }
    }
}

Projekt-Programowanie/Views/Home/Autorzy.cshtml
@{
    ViewData["Title"] = "Autorzy";
}
<h1>@ViewData["Title"]</h1>
<ul>
    <li><p>Grażyna Wyrtki</p></li>
    <li><p>Miłosz Krajczok</p></li>
    <li><p>Konrad Hoza</p></li>
</ul>

Projekt-Programowanie/Views/Home/Dodaj.cshtml
@using Projekt_Programowanie.Models.MODELS
@{
    ViewData["Title"] = "Dodaj pytanie lub odpowiedź";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 style="font-size:xx-large">Dodawanie elementów do bazy:</h4>
        </p>
        <div class="form-group">
            <div class="col-md-8 offset-2">
                <a style="color:forestgreen; font-family:'Baskerville Old Face'; font-size:x-large" class="nav-link" asp-area="" asp-controller="Word" asp-action="DodajSlowo">Dodaj Słowo</a>
            </div>
            <div class="col-md-8 offset-2">
                <a style="color:forestgreen; font-family:'Baskerville Old Face'; font-size:x-large" class="nav-link" asp-area="" asp-controller="Question" asp-action="DodajPytanie">Dodaj Pytanie</a>
            </div>
        </div>
    </div>
    </div>

Projekt-Programowanie/Views/Home/Generator1.cshtml
@using Projekt_Programowanie.Models.MODELS
@{
    ViewData["Title"] = "Dodaj pytanie lub odpowiedź";
}
@model Krzyzowka
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Generator Krzyżówki</h4>
        </p>
        <form method="post" asp-controller="Cross" asp-action="Generator">
            <div class="form-group">
                <div class="col-md-8 offset-2">
                    <label asp-for="Trudnosc">Trudność:</label>
                    <input asp-for="Trudnosc" class="form-select-sm" placeholder="1" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-8 offset-2">
                    <label asp-for="Wzor">Wzór:</label>
                    <input asp-for="Wzor" class="form-select-sm" placeholder="1" />
                </div>
            </div>
            <div class="form-group mt-3 mb-5">
                <input class="btn btn-outline-success float-right" type="submit" asp-controller="Cross" asp-action="Generator" value="Generuj"/>
            </div>
        </form>
    </div>
</div>

Projekt-Programowanie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 fw-bold">Witaj Przybyszu!</h1>
    <p>Oto nasz projekt strony z krzyżówkami panoramicznymi.</p>
</div>

Projekt-Programowanie/Views/Home/Listy.cshtml
@using Projekt_Programowanie.Models.MODELS
@{
    ViewData["Title"] = "Wyświetl listy:";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4 style="font-size:xx-large">Listy z bazy:</h4>
        </p>
        <div class="form-group">
            <div class="col-md-8 offset-2">
                <a style="color:forestgreen; font-family:'Baskerville Old Face'; font-size:x-large" class="nav-link" asp-area="" asp-controller="Word" asp-action="Word">Lista Słów</a>
            </div>
            <div class="col-md-8 offset-2">
                <a style="color:forestgreen; font-family:'Baskerville Old Face'; font-size:x-large" class="nav-link" asp-area="" asp-controller="Question" asp-action="Question">Lista Pytań</a>
            </div>
            <div class="col-md-8 offset-2">
                <a style="color:forestgreen; font-family:'Baskerville Old Face'; font-size:x-large" class="nav-link" asp-area="" asp-controller="Cross" asp-action="Cross">Lista Krzyżówek</a>
            </div>
        </div>
    </div>
</div>

Projekt-Programowanie/Views/Home/Opis.cshtml
@{
    ViewData["Title"] = "Opis";
}
<h1>@ViewData["Title"]</h1>
<ul>
    <p>
        Aplikacja ma pozwalać tworzyć krzyżówkę o
        określonym wzorze. Po stworzeniu daje użytkownikowi możliwość zachowania
        powstałej krzyżówki, lub wygenerowanie nowej. Użytkownik może przystąpić do
        rozwiązania krzyżówki. Po poprawnym ukończeniu wyświetli się wynik z ilością
        wykorzystanego czasu. Rozwiązaną krzyżówkę można przypisać do użytkownika.
        W czasie rozwiązywania krzyżówki poprawność nie jest sprawdzana na bieżąco,
        tylko po kliknięciu ‘sprawdź’ mając wszystkie słowa wpisane następuje
        weryfikacja poprawności wpisanych słów.
    </p>
</ul>